config/routes.rb
Rails.application.routes.draw do
  root to: 'profile#test'
  get '/profile/:username', to: 'profile#index'

  resources :ads do
    delete :delete_image_attachment
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  has_many :categories
  has_many_attached :images
  before_create :randomize_id



  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000)
    end while Ad.where(id: self.id).exists?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :ads
         acts_as_messageable


         def mailboxer_email(object)
          email
        end
end 

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :get_user, only: [:show ] 
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.order(created_at: :desc)
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)
    @ad.user_id = current_user.id

    respond_to do |format|
      if @ad.save
       format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    
    specific =  ActiveStorage::Attachment.find(params[:ad_id])
    specific.purge
    ad = Ad.find(params[:ad])
  
    redirect_to ad_url(ad)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end
    def get_user
      ad = Ad.find(params[:id])
      @user = User.find(ad.user_id)
    end

    def check_user
      user = User.find(@ad.user_id)
      if user.id != current_user.id
        redirect_to request.referrer, flash: {notice: "You can't edit any ad except your own."}
      end

    end

   

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :price, :description, :city, :postal, :province, :phone, :category, :user_id, images:[])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found'
    redirect_back_or root_path
    
end

def redirect_back_or(path)
    redirect_to request.referer || path 
end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_mailbox
    before_action :get_conversation, except: [:index]

    def index
    @conversations = @mailbox.inbox
    
    end

    def show

    end

    private

    def get_mailbox
        @mailbox ||= current_user.mailbox
    end

    def get_conversation
        @conversation ||= @mailbox.conversations.find(params[:id])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!


    def new 
    end


    def create 
        recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index

 @user = User.find_by_username(params[:username])
 @ad_count = @user.ads.count
 @cat = Category.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit(:fname, :lname, :province, :postal, :address, :addresstwo, :city, :username, :email, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:fname, :lname, :province, :postal, :address, :addresstwo, :city, :username, :email, :password, :password_confirmation, :current_password)
    end
  end

app/helpers/ads_helper.rb
module AdsHelper
    def display_picture(ad)

        if ad.images.attached?
            image_tag(url_for(ad.images.first))
        else 
            image_tag("placeholder.png");

        end
            
    end 

    def categories
        [
          ['Saltwater Fish'],
          ['Freshwater Fish'],
          ['Corals'],
          ['Aquariums']
        ]

      end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def can_prov
        [
          ['Alberta'],
          ['British Columbia'],
          ['Manitoba'],
          ['New Brunswick'],
          ['Newfoundland and Labrador'],
          ['Nova Scotia'],
          ['Ontairo'],
          ['Prince Edward Island'],
          ['Quebec'],
          ['Saskatchewan'],
          ['Northwest Territories'],
          ['Nunavat'],
          ['Yukon']
        ]
      end

      
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

    def recipients_options
        s = ''
        User.all.each do |user|
          s << "<option value='#{user.id}'>#{user.username}</option>"
        end
        s.html_safe
      end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad, local: true) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<div class="col s12">
<div class="row">
<div class="input-field col s6">
    <%= form.text_field :title, class: 'validate' %>
 <%= form.label :title %>
  
  </div>

  <div class="input-field col s6">
  
    <%= form.label :price %>
    <%= form.text_field :price, class: 'validate' %>
  
  </div>
  </div>
<div class="row">
  <div class="input-field col s6">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'materialize-textarea'%>
  </div>

  <div class="input-field col s6">
    <%= form.label :city %>
    <%= form.text_field :city, :value => current_user.city %>
  </div>
  </div>
<div class="row">
  <div class="input-field col s6">
    <%= form.label :postal %>
    <%= form.text_field :postal %>
  </div>

  <div class="input-field col s6">
   
    <%= form.select :province, options_for_select(can_prov, selected: current_user.province)  %>
     <%= form.label :province %>
  </div>
  </div>
<div class="row">

   <div class="file-field input-field col s6">
      <div class="btn">
        <span>File</span>
         <%= form.file_field :images, multiple: true, direct_upload: true %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="Upload one or more pictures">
      </div>
    </div>

  <div class="input-field col s6">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  </div>

   <div class="input-field col s6">
   
    <%= form.select :category, options_for_select(categories)  %>
     <%= form.label :category %>
  </div>
 </div>

  

  <div class="actions">
  <%= button_tag :submit, class:'btn waves-effect waves-light left' do %>
     <i class="material-icons right">create</i>create ad
  <% end %>
    
  </div>
<% end %>

app/views/ads/_sidebar.html.erb
<% categories %>


Sidebar

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col m6">
<h1>Ads</h1>
</div>
<div class="col m6"><%= link_to 'New Ad', new_ad_path, class: 'add_ad' %>
</div>
</div>


<div class="row">
 <div class="col m3 hide-on-small-only">
   <%= render partial: "sidebar" %>
    </div>
<div class="col m9 s12">
    <% @ads.each do |ad| %>
    <div class="col s12 ad_index">
    <div class="col s8">
    <div class="row">
     <h5 class="blue-text text-lighten-3"><%= ad.title %></h5>
     
   <em><%= number_to_currency(ad.price, precision: 2) %></em>
   </div>
   <div class="row">
       
     
        <div class="address"><i class="material-icons">place</i> <%= ad.city %>, <%= ad.province %>,  <%= ad.postal %>
        </div>

        <p><%= ad.description %></p>
        <%= ad.phone %>

        <div class="category">
        <%= ad.category %>
        </div>
        </div>
        </div>
        <div class="col s4">
        <%= display_picture(ad)%>
        
        </div>
        <div class="row">
        <div class="col m12">
        <%= link_to 'View', ad, class: 'waves-effect btn' %>
        </div>
      </div>
     
      
     </div>
     
    <% end %>
   
  </div>
<br>

app/views/ads/new.html.erb
<h1>New Ad</h1>


<%= render 'form', ad: @ad %>



 <%= button_tag ads_path, class:'btn waves-effect waves-light left' do %>
     <i class="material-icons right">arrow_back</i>Back
  <% end %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

<div class="col m4">

<% @ad.images.each do |image| %>
    <h5><%= image.filename %></h5>
    <%= image_tag url_for(image) %>
    <% if @user.id === current_user.id %>
  <%= link_to 'Remove', ad_delete_image_attachment_url(image.blob_id, @ad.id, :ad  => @ad.id ),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<% end %>

<% end %>
</div>


<div class="col m6">
<p>
  
 <h3> <%= @ad.title %></h3>
</p>

<p>
  
   <%= number_to_currency(@ad.price, precision: 2) %>
</p>

<p>
  <strong>Description:</strong>
 <p> <%= @ad.description %></p>
</p>

<p>
  <strong>City:</strong>
  <%= @ad.city %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @ad.postal %>
</p>

<p>
  <strong>Province:</strong>
  <%= @ad.province %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ad.phone %>
</p>

 

</div>

<div class="col m2">

<h4>Contact</h3>
<p>This ad was posted by <%= @user.fname %> </p>

<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'recipients', 'Choose recipients' %>
    <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>







</div>


<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>

app/views/conversations/index.html.erb
<ul>
<% @conversations.each do |conversation| %>
<li>
<%= link_to conversation.subject, conversation_path(conversation)   %>
</li>
<% end %>

</ul>

app/views/conversations/show.html.erb
<%= @conversation.subject %>

<% @conversation.receipts_for(current_user).each do |receipt| %>

<% message = receipt.message %>

<h3><%= message.sender.username %></h3>

<p><%= message.body %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aquarium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

 
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header> 
 <nav>
    <div class="nav-wrapper">
    <div class="container">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><%= link_to "Ads", ads_path %></li>
        <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
       
      </ul>
    </div>
    </div>
  </nav>
  </header>
<main>
 <div class="container">
    <%= yield %>
    </div>
    
  

    </main>

     <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
        
  </body>



  
</html>

app/views/messages/new.html.erb
<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'recipients', 'Choose recipients' %>
    <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>